repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: veba
  description: A modular end-to-end suite for in silico recovery, clustering, and
    analysis of prokaryotic, microeukaryotic, and viral genomes from metagenomes.
    Implemented in NextFlow.
  author: Josh L. Espinoza
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
