contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #veba channel"
    url: https://nfcore.slack.com/channels/veba
    about: Discussion about the nf-core/veba pipeline
